### PR TITLE
add logo/favicon

### PR DESCRIPTION
**Pull request by opadron**

### CODE REVIEW

**Review by waxlamp — CHANGES_REQUESTED** [review]
Code looks fine, but the images seems to be way too big. e.g., both images have ugly jags. Can we resize them appropriately?

**Comment by opadron** [comment]
@ronichoudhury checkout the files locally and view them with your viewer of choice.  Github doesn't display the images at scale, for some reason.

**Comment by manthey** [comment]
When I check out this branch, I see favicon.png and osumo-inv.png both as 606x606 pixels in size.

**Comment by manthey** [comment]
Also, I recommend any png we include for use across the web to be run through a tool such as [optipng](http://optipng.sourceforge.net/), which can reduce the png size substantially without any functional change by choosing different compression options.

**Comment by opadron** [comment]
@manthey wow, you're right!  No idea how that happened.  (favicons aren't even supposed to work unless they are 32x32).

**Comment by manthey** [comment]
Historically, they started as 16x16 .ico files...  But all the major browsers support PNG, and many will work with whatever you toss them.  Lots of devices work with different sizes, from 16x16 to 192x192.

**Comment by opadron** [comment]
@ronichoudhury PTAL.  I guess github does display images at scale. :)

**Comment by opadron** [comment]
Also, I went ahead and ran the images through optipng @manthey.  I got ~20% savings in the favicon, and ~30% in the main logo.  Neat! :+1:

**Pull request merged**
