### PR TITLE
Marketing materials import

### PR DESCRIPTION
**Pull request by waxlamp**
- [x] Import marketing front page materials
- [x] Import marketing "modal" materials (project-specific information)
- [ ] Update pictures for papers to images from papers

### CODE REVIEW

**Comment by jeffbaumes** [comment]
Just took a look. I say we just delete the two project thumbnails since they are repeated directly below. Also I'd remove the "Home" heading. Other than that it looks pretty reasonable for a first take on it.

**Comment by waxlamp** [comment]
Done.

**Comment by jeffbaumes** [comment]
Want to take the WIP off the PR title?

**Comment by waxlamp** [comment]
I think David is making a few tweaks as we speak, so I'll let him strip the
WIP.

**Comment by waxlamp** [comment]
I did several tweaks, described in the list of commits. Let me know if it looks right.

**Comment by manthey** [comment]
It looks much better now.

**Comment by jeffbaumes** [comment]
LGTM!

**Comment by opadron** [comment]
Thanks, everybody!  For the time being, we should keep the marketing branch and this PR open.  I will be deploying from it for the demo.

After the demo, we'll get together, produce a polished version of everything in here, get those merged in, and then close this.

**Comment by waxlamp** [comment]
@opadron, just FYI, I made sure to base this PR against the `job-runner` branch, so if you like you could merge this PR and that way we'd have one less branch to worry about. It is of course up to you.

**Comment by opadron** [comment]
@ronichoudhury oh!  In that case, I'm merging this bad boy!

While we're at it, we should probably rename `job-runner` to something that better describes the changes.  For example, I'm using `demo-2016-04-08` in the osumo-project repo.

...probably should tag it, too...

**Pull request merged**
