### PR TITLE
Upgrade deps

### PR DESCRIPTION
**Pull request by opadron**
continued from #24

### CODE REVIEW

**Comment by opadron** [comment]
Also, this update should work with the latest versions of node, girder, and girder_worker.

**Comment by opadron** [comment]
Build failure is probably the same as angular/angular-cli#2477

**Comment by waxlamp** [comment]
I'm still having trouble doing `npm run build`. I'd recommend we go with #26

**Comment by opadron** [comment]
Okay, this should be ready for review.

There is a known issue related to the process data tab.  The state is not properly initialized, and therefore leaving the file inputs at their defaults results in undefined behavior when a job is submitted.

@manthey is looking into a hotfix, while I am moving on and working on the new architecture, which should fix this known issue, as well.

So please leave this issue out of the review, for now, whoever gets to it.

**Comment by opadron** [comment]
Not sure why the builds are failing.  All of the building fixes should have been added, already.

**Comment by manthey** [comment]
Do they pass locally?

**Comment by opadron** [comment]
Yes, I tried using the same version of node and everything.

**Comment by manthey** [comment]
I think the failure was due to npm caching issues.  Perhaps adding `npm update` prior to `npm prune` would have fixed the problem without blowing away travis caches.  Or you might also need to get rid of `~/.npm` or its equivalent in travis, too.

**Comment by opadron** [comment]
That's a good idea.  I'll give it a shot.

**Comment by opadron** [comment]
@manthey looks like that did the trick.

**Comment by manthey** [comment]
LGTM.

**Pull request merged**
